### ISSUE TITLE
Installer corrupt [composer hash]

### ISSUE THREAD

**Issue by 5shekel** [chiefy/docker-mediawiki#2]
hi , thanks for the image

the hardcoded hash for the php composer thru `Installer corrupt` error 

the [official word from composer site](https://getcomposer.org/doc/faqs/how-to-install-composer-programmatically.md) is is either use a script to do the hash validation. or wget a specific version from trusted github server
`wget https://raw.githubusercontent.com/composer/getcomposer.org/76a7060ccb93902cd7576b67264ad91c8a2700e2/web/installer -O - -q | php -- --quiet`

**Comment by chiefy** [comment]
@5shekel fixed in master / updated to `1.33.1` as well
